identifier: checkout-api 
title: Checkout API
blueprint: service
properties:
  language: nodejs
  tier: tier1
  repository: https://github.com/walmart-platform-lab/checkout-api
relations:
  owner: team-checkout
